# Homebrew formula for ctx â€” installed from prebuilt release binaries.
#
# Tap repository layout:
#   <tap>/
#     Formula/
#       ctx.rb            <- this file
#
# Usage:
#   brew tap halloffame12/CTX
#   brew install ctx
#
# Generated by scripts/update-homebrew.sh â€” do not edit by hand.
class Ctx < Formula
  desc "Codebase intelligence and context engine for AI coding agents"
  homepage "https://github.com/halloffame12/CTX"
  version "0.1.3"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/halloffame12/CTX/releases/download/v0.1.3/ctx-macos-aarch64"
    sha256 "4455cd2223f020fd8693e95dce62ad9ce4fe0aa749c07ba48d0beee1a39443a3"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/halloffame12/CTX/releases/download/v0.1.3/ctx-macos-x86_64"
    sha256 "f99b99eba3f80095fb3a3f0b7b47d71b034a9cb64bb810e9818a68cce722729f"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/halloffame12/CTX/releases/download/v0.1.3/ctx-linux-aarch64"
    sha256 "5020a54b39313a7c9dbe5a088ee755ee343665fd5c487e5e11f1f959fb81cc96"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/halloffame12/CTX/releases/download/v0.1.3/ctx-linux-x86_64"
    sha256 "f8e6ea4101ac5cc7586c7c10c89cfedd4e89bc7c0e641d68b8aeaaf9912094c0"
  else
    odie "ctx: unsupported platform â€” only macOS (Intel/ARM) and Linux (Intel/ARM) are supported"
  end

  def install
    bin.install Dir["ctx-*"].first => "ctx"
  end

  test do
    assert_match "ctx #{version}", shell_output("#{bin}/ctx --version")
  end
end
