# Homebrew formula for ctx — installed from prebuilt release binaries.
#
# Tap repository layout:
#   <tap>/
#     Formula/
#       ctx.rb            <- this file
#
# Usage:
#   brew tap halloffame12/ctx
#   brew install ctx
#
# Generated by scripts/update-homebrew.sh — do not edit by hand.
class Ctx < Formula
  desc "Codebase intelligence and context engine for AI coding agents"
  homepage "https://github.com/halloffame12/CTX"
  version "0.1.0"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/halloffame12/CTX/releases/download/v0.1.0/ctx-macos-aarch64"
    sha256 "d9e925dae8c9af689fe70f47201f094b3d439a7217e48a63b9eceedf49a7452a"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/halloffame12/CTX/releases/download/v0.1.0/ctx-macos-x86_64"
    sha256 "9918d841649a14c431fb644b5a6a152e682129639ab1182356721c27bb21ea42"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/halloffame12/CTX/releases/download/v0.1.0/ctx-linux-aarch64"
    sha256 "ab9322b26d0f81986331da68ae36a7d27f9aa237a4a383b6d15f98e1c5764415"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/halloffame12/CTX/releases/download/v0.1.0/ctx-linux-x86_64"
    sha256 "4e7a58ff084f4e1a5f2897c5e50444c755f859f4be1cb815cff14069077b8449"
  else
    odie "ctx: unsupported platform — only macOS (Intel/ARM) and Linux (Intel/ARM) are supported"
  end

  def install
    bin.install Dir["ctx-*"].first => "ctx"
  end

  test do
    assert_match "ctx #{version}", shell_output("#{bin}/ctx --version")
  end
end
